// src/react/components/Modal.tsx
import React, { Fragment, useState, useCallback } from 'react';
import type { ComponentType } from 'react';

import VectorImage from './VectorImage';
import Counter from './Counter';
import WindowEvent from './WindowEvent';

import { close } from '../store/showStore';
import { useDispatch } from 'react-redux';

const componentsMap: Record<string, ComponentType> = {
    VectorImage,
    Counter,
    WindowEvent,
};

interface Props {
    msg: string;
}

export default function Modal(props: Props) {
    const [currentView, setCurrentView] = useState('VectorImage');
    const ComponentToRender = componentsMap[currentView];
    const { msg } = props;
    const dispatch = useDispatch();

    const _close = useCallback(
        (event: React.MouseEvent<HTMLDivElement, MouseEvent>) => {
            event.stopPropagation();
            if (event.target === event.currentTarget) {
                dispatch(close());
            }
        },
        [dispatch],
    );
    return (
        <Fragment>
            <div className='framework-test-modal-mask' onClick={_close}>
                <div className='framework-test-modal-container'>
                    <span>
                        <button className='framework-test-modal-close-button' onClick={() => dispatch(close())}>
                            &times;
                        </button>
                    </span>
                    <div className='container-fluid text-center'>
                        <div className='row'>
                            <div className='col-2'>
                                <p className='framework-test-header-react framework-test-heavy'>{msg}</p>
                                <div className='btn-group-vertical' role='group'>
                                    <button type='button' className={currentView === 'VectorImage' ? 'btn btn-framework-test btn-framework-test-react' : 'btn btn-framework-test'} onClick={() => setCurrentView('VectorImage')}>
                                        Vector Image
                                    </button>
                                    <button type='button' className={currentView === 'Counter' ? 'btn btn-framework-test btn-framework-test-react' : 'btn btn-framework-test'} onClick={() => setCurrentView('Counter')}>
                                        Counter
                                    </button>
                                    <button type='button' className={currentView === 'WindowEvent' ? 'btn btn-framework-test btn-framework-test-react' : 'btn btn-framework-test'} onClick={() => setCurrentView('WindowEvent')}>
                                        Window Event
                                    </button>
                                </div>
                            </div>

                            <div className='col-8'>
                                <ComponentToRender />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Fragment>
    );
}

// src/solid/components/Modal.tsx
import { createSignal } from 'solid-js';
import type { JSX } from 'solid-js';

import VectorImage from './VectorImage';
import Counter from './Counter';
import WindowEvent from './WindowEvent';

import { setShow } from '../signal/showSignal';

const componentsMap: Record<string, () => JSX.Element> = {
    VectorImage,
    Counter,
    WindowEvent,
};

interface Props {
    msg: string;
}

export default function Modal(props: Props) {
    const [currentView, setCurrentView] = createSignal<string>('VectorImage');

    const { msg } = props;

    function _close(event: Event) {
        event.stopPropagation();
        if (event.target === event.currentTarget) {
            setShow(false);
        }
    }

    return (
        <div class='framework-test-modal-mask' onClick={_close}>
            <div class='framework-test-modal-container'>
                <span>
                    <button class='framework-test-modal-close-button' onClick={() => setShow(false)}>
                        &times;
                    </button>
                </span>
                <div class='container-fluid text-center'>
                    <div class='row'>
                        <div class='col-2'>
                            <p class='framework-test-header-solid framework-test-heavy'>{msg}</p>
                            <div class='btn-group-vertical' role='group'>
                                <button type='button' class={currentView() === 'VectorImage' ? 'btn btn-framework-test btn-framework-test-solid' : 'btn btn-framework-test'} onClick={() => setCurrentView('VectorImage')}>
                                    Vector Image
                                </button>
                                <button type='button' class={currentView() === 'Counter' ? 'btn btn-framework-test btn-framework-test-solid' : 'btn btn-framework-test'} onClick={() => setCurrentView('Counter')}>
                                    Counter
                                </button>
                                <button type='button' class={currentView() === 'WindowEvent' ? 'btn btn-framework-test btn-framework-test-solid' : 'btn btn-framework-test'} onClick={() => setCurrentView('WindowEvent')}>
                                    Window Event
                                </button>
                            </div>
                        </div>
                        <div class='col-8'>{componentsMap[currentView()]()}</div>
                    </div>
                </div>
            </div>
        </div>
    );
}
