// src/svelte/components/WindowEvent.svelte
<script lang="ts">
    import { onMount } from 'svelte';

    import { windowProxy } from '../../common/utils/tamperMonkeyFunction';
    const sharedState = {
        search: windowProxy.scriptTemplate?.search || '',
    };
    onMount(() => {
        windowProxy.addEventListener('kwChanged', () => {
            sharedState.search = windowProxy.scriptTemplate?.search || '';
        });
    });
</script>

<div class="block">
    <div class="subtitle is-2 header-framework-test-svelte">Window Event, Value is {sharedState.search}</div>
</div>

// src/vue/components/WindowEvent.vue
<template>
    <div class="block">
        <div class="subtitle is-2 header-framework-test-vue">Window Event, Value is {{ sharedState.search }}</div>
    </div>
</template>

<script setup lang="ts">
    import { reactive, onMounted } from 'vue';

    import { windowProxy } from '../../common/utils/tamperMonkeyFunction';

    const sharedState = reactive({
        search: windowProxy.scriptTemplate?.search || '',
    });
    onMounted(() => {
        windowProxy.addEventListener('kwChanged', () => {
            sharedState.search = windowProxy.scriptTemplate?.search || '';
        });
    });
</script>
