// src/react/components/Counter.tsx
import React from 'react';

import { useDispatch, useSelector } from 'react-redux';
import { increment, decrement, count } from '../store/counterStore';

export default function Counter() {
    const dispatch = useDispatch();
    const _count = useSelector(count);
    return (
        <React.Fragment>
            <div>
                <h1>Counter</h1>
                <p>Count: {_count}</p>
                <div className='container text-center'>
                    <div className='row align-items-center'>
                        <div className='col-4'></div>
                        <div className='col-2'>
                            <button type='button' className='btn btn-lg btn-framework-test-react' onClick={() => dispatch(increment())}>
                                Increment
                            </button>
                        </div>
                        <div className='col-2'>
                            <button type='button' className='btn btn-lg btn-framework-test-react' onClick={() => dispatch(decrement())}>
                                Decrement
                            </button>
                        </div>
                        <div className='col-4'></div>
                    </div>
                </div>
            </div>
        </React.Fragment>
    );
}

// src/svelte/components/Counter.svelte
<script lang="ts">
    import { count, increment, decrement } from '../store/counterStore';
</script>

<div>
    <h1>Counter</h1>
    <p>Count: {$count}</p>
    <div class="container text-center">
        <div class="row align-items-center">
            <div class="col-4"></div>
            <div class="col-2"><button type="button" class="btn btn-lg btn-framework-test-svelte" on:click={increment}>Increment</button></div>
            <div class="col-2"><button type="button" class="btn btn-lg btn-framework-test-svelte" on:click={decrement}>Decrement</button></div>
            <div class="col-4"></div>
        </div>
    </div>
</div>
