// src/components/HelloWorld.vue
<template>
    <div>
        <h1>{{ msg }}</h1>
        <h3 class="test-class">Vue</h3>
        <ul class="test-class">
            <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>
            <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>
            <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>
            <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>
            <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>
            <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>
        </ul>
    </div>
</template>

<script setup lang="ts">
defineProps({
    msg: String,
});
</script>

<style>
h3.test-class {
    margin: 40px 0 0;
}
ul.test-class {
    list-style-type: none;
    padding: 0;
}
ul.test-class > li {
    display: inline-block;
    margin: 0 10px;
}
ul.test-class > li > a {
    color: #42b983;
}
</style>

// src/react/components/HelloWorld.tsx
import React from 'react';

interface Props {
    msg: string;
}

export default function HelloWorld(props: Props) {
    const { msg } = props;
    return (
        <React.Fragment>
            <div>
                <h1>{msg}</h1>
                <h3 className='react-test-class'>React Test Page</h3>
                <ul className='react-test-class'>
                    <li>
                        <a className='react-test-class-vue' href='https://vuejs.org' target='_blank' rel='noopener'>
                            Vue
                        </a>
                    </li>
                    <li>
                        <a className='react-test-class-pinia' href='https://pinia.vuejs.org' target='_blank' rel='noopener'>
                            Pinia
                        </a>
                    </li>
                    <li>
                        <a className='react-test-class-react' href='https://react.dev' target='_blank' rel='noopener'>
                            React
                        </a>
                    </li>
                    <li>
                        <a className='react-test-class-redux' href='https://redux.js.org' target='_blank' rel='noopener'>
                            Redux
                        </a>
                    </li>
                    <li>
                        <a className='react-test-class-less' href='https://lesscss.org' target='_blank' rel='noopener'>
                            Less
                        </a>
                    </li>
                    <li>
                        <a className='react-test-class-sass' href='https://sass-lang.com' target='_blank' rel='noopener'>
                            Sass
                        </a>
                    </li>
                    <li>
                        <a className='react-test-class-stylus' href='https://stylus-lang.com' target='_blank' rel='noopener'>
                            Stylus
                        </a>
                    </li>
                </ul>
            </div>
        </React.Fragment>
    );
}
